global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus自体を監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Node Exporter（ホストOSのメトリクス）
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # PostgreSQL Exporter（Postgresのメトリクス）
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Nginx Exporter（Nginxのリクエストとか）
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']
