global:
  scrape_interval: 15s

# alertmanagerのアドレス
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# alertmanagerのルール
rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus自体を監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Pushgateway（短命ジョブのメトリクス）
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  # Node Exporter（ホストOSのメトリクス）
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # PostgreSQL Exporter（Postgresのメトリクス）
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Nginx Exporter（Nginxのリクエストとか）
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'nginx-log'
    static_configs:
      - targets: ['nginx-log-exporter:4040']
