listen:
  port: 4040
  metrics_endpoint: /metrics

namespaces:
  - name: nginx
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
    source:
      files:
        - /var/log/nginx/access.log
    labels:
      app: "nginx"
